Feature/use dockerfile from project
panter/catladder pull request #15
Opened 2017-11-06 13:51 UTC by Blurri

2017-11-06 14:01 UTC, macrozone commented
i think that providing the dockerfile is a good solution for some cases, but we need a very specific docker file in the meteor case.

and i don't like that for meteor < 1.6 you can just user catladder without creating a dockerfile first and with 1.6 you have to create a dockerfile. Either both cases need a manual docker file or none.

i would suggest that 

- we keep this logic for later
- we add a nodeVersion config somewhere and that gets written in this auto-generated dockerfile

2017-11-06 14:02 UTC, macrozone requested changes

2017-11-06 14:02 UTC, macrozone commented on src/deployments/panter-meteor-kubernetes/push.js
> +  if (fs.existsSync('./Dockerfile')) {
what's this path refering to?

2017-11-07 09:05 UTC, Blurri commented
I try to add the nodeVersion as soon as possible.

2017-12-19 09:21 UTC, closed without merging